# Generated by Django 4.0.4 on 2022-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_chat_id_alter_message_id_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phrase',
            field=models.CharField(max_length=300),
        ),
    ]
